### ISSUE TITLE
Add parameter for skipping backups only

### ISSUE THREAD

**Issue by fgrehm** [Helabs/jumpup-heroku#60]
Today on the EP project we have a need to skip backup tasks because the postgresql DB in use is not provided by the Heroku addon.

jumpup-heroku allow us to skip ALL dbs tasks but we need a fine grained control over what is going to be skipped as we still want to run migrations during a deploy

**Comment by marcioj** [comment]
Hi @fgrehm, #70 which enable the SKIP_BACKUP option was merged and will be available in the next version.

**Comment by fgrehm** [comment]
:thumbsup:
