### ISSUE TITLE
Change the script for pgbackups

### ISSUE THREAD

**Issue by guiloyins** [Helabs/jumpup-heroku#72]
Since the Heroku addon pgbackups no longer exists and his functionality exist as part of the Heroku CLI, some changes in capture and destroy script will be needed.

More info [here](https://devcenter.heroku.com/articles/mapping-pgbackups-commands)

**Comment by marcioj** [comment]
Fixed by 34bb7c2eb90d56978d6a761ad63a18cf3be5cde5
